# =====================================================
#   Properties that will be shared amongst all modules
# =====================================================
sonar.language=java
sonar.java.source=17
sonar.sourceEncoding=UTF-8
sonar.scm.exclusions.disabled=true
sonar.sources=src/main/java
sonar.coverage.jacoco.xmlReportPaths=/workdir/src/target/jacoco-report/jacoco.xml
sonar.exclusions=/workdir/src/test/java/**,**/entity/**,**/constants/**,**/PermitDataManagementApplication.java,**/model/**,**/dto/**,**/logging/**,**/exception/**,**/configuration/**
sonar.java.binaries=/workdir/src/target/classes