#Database
#datasource.host=postgres-installationpermitmgt-dev.service.us-east4-npe.consul
datasource.host=postgres-installationpermitmgt-stage.service.us-east4-npe.consul

maxSize=2
initialSize=1
maxIdleTime=600000
maxCreateConnectionTime=5000
maxAcquireTime=2000
maxLifeTime=3600000
#SSL config
ca.ssl=true
ca.sslmode=verify-ca

#SecretFileLocation
file.location.secrets=secrets.json
#file.location.secrets=secrets-permits.json

# HTTP Connection Timeout in Milliseconds
http.connection.timeout=60000


#Metrics
management.endpoints.web.exposure.include=*
management.metrics.enabled=true
management.prometheus.metrics.export.enabled=true
management.metrics.export.server.port=8080
management.metrics.distribution.percentiles.all=0.5,0.75,0.95

spring.application.name=permit-data-management

# Mongo
spring.mongodb.database=permits
spring.data.mongodb.connection.pool.initialSize=1
spring.data.mongodb.connection.pool.maxSize=10
spring.data.mongodb.connection.pool.maxIdleTime=60
spring.data.mongodb.connection.pool.timeout=5000
spring.data.mongodb.connection.pool.life.time=60
spring.data.mongodb.connection.pool.idle.time=60
spring.data.mongodb.trust.store.path=C:/Users/c8982682/permitManagement/mongodetails/permitmanagement/paymentservicestrust.jks
cors.allowed-origins=*

server.port=8085
common.utility.api.host.url=https://internal-sadc-dev.carbon.lowes.com/services-common-utility
#items.url = http://localhost:8080/utils/bifrost/items
common.utility.bifrost.items.url = https://internal-sadc-stage.carbon.lowes.com/job-management-utility-service/utils/bifrost/items

document.bucket.name=installiq-documentsperf
document.access.name=S8WQ29RPRSTO25V508CV
document.url=https://obj-centraldtq.storage.lowes.com:443
document.access.secret=A73fwdtn70oFwGpNs/wD+V8ffNpp1/1SItH/mmVp
