spring.application.name=permit-data-management
spring.codec.max-in-memory-size=5MB
spring.jackson.default-property-inclusion=NON_NULL
spring.jackson.parser.allow-numeric-leading-zeros=true
spring.jackson.mapper.sort-properties-alphabetically=false
spring.data.mongodb.representation.big-decimal=STRING
spring.cache.caffeine.spec=expireAfterWrite=10m,maximumSize=1000
springdoc.api-docs.path=/v3/api-docs
# Database
datasource.host=postgres-installationpermitmgt-stage.service.us-east4-npe.consul
initialSize=10
maxSize=100
maxIdleTime=100000
maxAcquireTime=10000
maxCreateConnectionTime=10000
maxLifeTime=10000
# SSL
ca.ssl=true
ca.sslmode=verify-ca
# Secrets
file.location.secrets=secrets-permits.json
# HTTP
http.connection.timeout=60000
# Logging
logging.file.name=/var/log/Application.log
logging.level.root=INFO
logging.level.org.hibernate.SQL=INFO
logging.pattern.file=%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n
logging.pattern.level=%X{trace-id} %5p
# Metrics
management.endpoints.web.exposure.include=*
management.metrics.enabled=true
management.metrics.export.server.port=8080
management.prometheus.metrics.export.enabled=true
# Schedulers
scheduler.labor-category.cron=0 0 2 * * *
scheduler.permit-entity.cron=0 0 1 * * *
scheduler.permit-entity-retry.cron=0 0 * * * *
scheduler.permit-export.cron=0 30 1 * * *
# Labor category exclusions
labor-category-excluded-list=94,95,117,118,97,192,98,315,316,319,327,214,122,262,323,89,265,90,91,93,92,251,187,259,102,162,124,127,103,230,246,125,101,128,249,129,260,99,96,264,100,269,270,235,123,104,105,223,106,116,248,220,273,272,194,108,195,274,109,180,110,112,113,266,256,191,267,268,255,206,131,257,314,114,219,115